### ISSUE TITLE
Arguments of detect.py

### ISSUE THREAD

**Issue by wjassim** [fcakyon/yolov5-pip#31]
Hi. 
Thank you for the package. I have installed yolov5-pip and it works perfectly. Is it possible to pass the argument options such --classes, --line-thickness etc. (given in detect.py) via yolov5.predict or model(img)?

**Comment by fcakyon** [comment]
Hello @wjassim. `.predict` is the function for getting base predictions. It cannot have --line-thickness as input since it does not plot the predictions, it just returns a Detections object.

What you should do is to download [detect.py](https://github.com/fcakyon/yolov5-pip/blob/main/yolov5/detect.py) script. Right click in the `raw` button, then click on `save link as`.

You dont need to download or setup anything else. Just `pip install yolov5` and you can run `detect.py` with any argument from any folder directory :)

If you have any question feel free to ask.

**Comment by wjassim** [comment]
Thank you @fcakyon. I think I managed to access to the model setting using:

import torch
from yolov5 import YOLOv5

device = "cuda" # or "cpu"
# init yolov5 model
yolov5 = YOLOv5('weights/yolov5s6.pt', device)

then by using yolov5.model. I can change some parameters in the model (ex. yolov5.model.classes = [0,1,2]). Does it sound ok?

**Comment by fcakyon** [comment]
@wjassim yes that is a valid usage, you can always change the model parameters after initializing as you have mentioned :+1:

**Comment by fcakyon** [comment]
@wjassim you can also check the [yolov5-norfair integration for object tracking](https://github.com/fcakyon/norfair/tree/yolov5/demos/yolov5)

**Comment by wjassim** [comment]
That's very impressive. Thank you very much @fcakyon. I'll try it out now.

**Comment by wjassim** [comment]
Hi @fcakyon . yolov5-norfair integration for object tracking works perfectly. 

Maybe the centroid of the bbox can be extracted from the model as a list directly?
line 40 in yolov5demo.py: detections_as_xywh = detections.pandas().xywh[0]
centroid = np.array([[detections_as_xywh [0],detections_as_xywh [1]]])
 
thanks a million..

**Comment by fcakyon** [comment]
Hello @wjassim. Unfortunately that wouldnt work since 0 and 1 indexes are top left coordinates (not center): https://github.com/ultralytics/yolov5/blob/19100ba00709243976b1a31033be019816496cbd/utils/general.py#L319

**Comment by wjassim** [comment]
oh sorry, I thought the function xyxy2xywh normally converts [x1, y1, x2, y2] to [xcenter, ycenter, w, h] where xy1=top-left, xy2=bottom-right. Thanks for the note.

**Comment by fcakyon** [comment]
@wjassim my bad, you are definitely right. Updated the detection format conversion as you said :) https://github.com/fcakyon/norfair/tree/yolov5/demos/yolov5
