### ISSUE TITLE
Maintenance Concerns

### ISSUE THREAD

**Issue by glenn-jocher** [fcakyon/yolov5-pip#4]
@fcakyon is there a way to automate pip package maintenance so that the package stays up to date with ultralytics/yolov5 master without having to manually update code and push new versions? Maybe a weekly schedule would make sense.

This might prevent problems like https://github.com/fcakyon/yolov5-pip/issues/3. I don't have any recommendations myself since I'm not a pip expert, but I can see a problem if features or bug fixes start to divert between master and this yolov5 package. What do you think?

**Comment by fcakyon** [comment]
@glenn-jocher your concerns are right.

Main branch of this yolov5-pip repo was the copy of release v4.0 of ultralytics/yolov5 repo. I was thinking on updating the pip package after your each new major release. But it turns out that even major releases are open for updates/new features.

Now i am working on a new version:
- it will support torch hub way by default, but torch hub way is not always practical because most people want to work on a stable version instead of the latest version of ultralytics/yolov5
- it will also support weekly snapshots of ultralytics/yolov5
(user will be able to select one of these two options while initializing the YoloV5 class)

I think once I finish this version, your concerns will be addressed.

**Comment by glenn-jocher** [comment]
@fcakyon that's a great idea to mirror the pytorch hub functionality, I was going to mention that as well. Then everyone gets the same UX whether they use hub yolov5 or pip yolov5.

I try to save major releases, i.e. next will be v5.0 for actual model updates, and minor release, i.e. v5.1 for other changes, but I also don't want to introduce frequent minor releases, as things are complicated already, so I usually urge people to clone nightly as things typically updating quickly. 

The commit/PR count since last release is actually displayed in the YOLOv5 commands here (111 commits since v4.0 release), unfortunately we need to commit frequently due to the fast pace of development.
```
YOLOv5 v4.0-111-gab86cec torch 1.7.1+cu101 CUDA:0 (Tesla V100-SXM2-16GB, 16160.5MB)
```

**Comment by robmarkcole** [comment]
The icevision guys created a script to keep their published fork up to date https://github.com/airctic/yolov5-pip-converter

**Comment by robmarkcole** [comment]
@fcakyon it has a dependency on [icevision](https://pypi.org/project/icevision/), but what might be useful is the approach used

**Comment by fcakyon** [comment]
Yes the approach is interesting, I might utilize it in this repo.

**Comment by FraPochetti** [comment]
@fcakyon indeed, `yolov5-icevision` was built to tightly work with `icevision` so we just made sure the pieces we needed were working properly, not the entirety of the repo.

**Comment by fcakyon** [comment]
@FraPochetti I totally understand that. I also love what your are doing in icevision, its a very useful project 👍
